# 基础镜像
FROM nginx
# author
MAINTAINER demo

# 挂载目录
VOLUME /home/demo/projects/demo-ui
# 创建目录
RUN mkdir -p /home/demo/projects/demo-ui
# 指定路径
WORKDIR /home/demo/projects/demo-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/demo/projects/demo-ui
